# Generated by Django 2.2 on 2021-04-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210425_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='api.Student'),
        ),
    ]
