# Generated by Django 2.2.12 on 2021-05-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210512_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
        ),
    ]
